version: "3.7"
services:
  grpc-server:
    build:
      context: ./grpc-server
      dockerfile: Dockerfile
    environment:
      DATABASE_SOURCE: root@tcp(db:3306)/adventar_dev
    depends_on:
      - db
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - grpc-server
    ports:
      - 8000:8000
    command: /usr/local/bin/envoy -c /etc/envoy/envoy-dev.yaml
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: adventar_dev
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 13306:3306
    volumes:
      - db-data:/var/lib/mysql"

volumes:
  db-data:
